# -*- coding: utf-8 -*-
"""Actividad2_VEML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ayLlhVYxBKBjY6nA_BoAE5H2iLjAWN-

<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:28px; border-radius:8px; box-shadow:0 2px 8px #00004733;" src='alinco.png' width="120"/>
<div style="margin-left:150px;">
<h1 style="color:#000047; font-size:2.3em; margin-bottom:0;">Actividad 2</h1>
<h2 style="color:#003366; font-size:1.3em; margin-top:0;">Identificación, Preprocesamiento y Distribución de los datos</h2>
</div>
<br style="clear:both"/>
</div>



<div style="border-left:6px solid #000047; padding:18px; margin-top:18px; background:#f5f5f5; border-radius:8px;">
<span style="font-size:1.1em;"><b>Objetivo:</b>
Practicar los métodos vistos en clase para la identificación de datos faltantes, outliers y análisis de la distribución de los datos, utilizando herramientas estadísticas y visuales modernas.</span>
<ul style="margin-top:10px;">
<li>Aplicar técnicas de análisis exploratorio de datos (EDA) para comprender la calidad y forma de los datos.</li>
<li>Identificar y tratar valores atípicos (outliers) tanto univariados como multivariados.</li>
<li>Visualizar y comparar distribuciones para tomar mejores decisiones en el preprocesamiento.</li>
</ul>
</div>

<div style="margin-top:18px; background:#f0f7ff; border-radius:8px; padding:14px; border:1px solid #b3c6ff;">
<b>Instrucciones generales:</b>
<ul style="margin-bottom:0;">
<li>Lee cuidadosamente cada sección y realiza los ejercicios propuestos.</li>
<li>Utiliza <b>la librería creada (HyAIA) en clase</b> para contestar lo que se pide.</li>
<li>Incluye comentarios y conclusiones breves en cada sección para reflexionar sobre los resultados obtenidos.</li>
<li>Recuerda que puedes agregar celdas de código o markdown adicionales si lo consideras necesario para explicar tu proceso.</li>
</ul>
</div>

<div style="margin-top:18px; background:#fffbe6; border-radius:8px; padding:12px; border:1px solid #ffe066;">
<b>Tip:</b> Aprovecha las funciones de visualización para interpretar mejor los resultados y justificar tus respuestas.
</div>

<h2 style="color:#003366; margin-top:0;">1. Medidas de posición y de forma <span style='font-size:0.7em; color:#888;'>&#128202;</span></h2>
<p style="font-size:1.1em;">
En esta sección analizarás el <b>dataset <code>tips</code> de la librería <code>seaborn</code></b> para practicar el análisis de calidad, distribución y forma de los datos.
</p>
<ul style="font-size:1.05em;">
<li><b>1.</b> <span style='color:#000047;'>Carga el dataset:</span> <code>sns.load_dataset('tips')</code></li>
<li><b>2.</b> <span style='color:#000047;'>Reporte de calidad:</span> Usa <code>dqr()</code> para obtener un resumen de los datos.</li>
<li><b>3.</b> <span style='color:#000047;'>Asimetría y curtósis:</span> Calcula estos valores para cada columna numérica.</li>
<li><b>4.</b> <span style='color:#000047;'>Visualización:</span> Grafica la distribución y medidas de forma de <code>total_bill</code>.</li>
<li><b>5.</b> <span style='color:#000047;'>Comparación por día:</span> Compara asimetría y curtósis de <code>total_bill</code> por <code>day</code>.</li>
<li><b>6.</b> <span style='color:#000047;'>Cuartiles:</span> Calcula los cuartiles de <code>tip</code>.</li>
<li><b>7.</b> <span style='color:#000047;'>Diagrama de cajas:</span> Visualiza <code>tip</code> y comenta tus observaciones.</li>
</ul>
<div style="margin-top:12px; background:#e6f2ff; border-left:4px solid #003366; padding:10px 18px; border-radius:8px;">
<b>Consejo:</b> Utiliza gráficos como histogramas, boxplots y tablas resumen para enriquecer tu análisis.
</div>
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import skew, kurtosis

sns.set(style="whitegrid")

tips = sns.load_dataset("tips")
tips.head()

def dqr(df):
    dqr_df = pd.DataFrame({
        'Tipo': df.dtypes,
        'Valores Nulos': df.isnull().sum(),
        'Valores Únicos': df.nunique(),
        'Mínimo': df.select_dtypes(include=[np.number]).min(),
        'Máximo': df.select_dtypes(include=[np.number]).max(),
        'Media': df.select_dtypes(include=[np.number]).mean(),
        'Desv Est': df.select_dtypes(include=[np.number]).std()
    })
    return dqr_df

dqr(tips)

# Asimetría y curtósis
num_cols = tips.select_dtypes(include=[np.number])

asimetria = num_cols.apply(skew)
curtosis = num_cols.apply(kurtosis)

print("Asimetría:")
print(asimetria, "\n")

print("Curtosis:")
print(curtosis)

# Visualización
plt.figure(figsize=(10,5))
sns.histplot(tips.total_bill, kde=True)
plt.title("Distribución de total_bill")
plt.show()

print("Asimetría total_bill:", skew(tips.total_bill))
print("Curtosis total_bill:", kurtosis(tips.total_bill))

# Comparación por día
dias = tips['day'].unique()

for d in dias:
    subset = tips[tips['day'] == d]['total_bill']
    print(f"\nDía: {d}")
    print("  Asimetría:", skew(subset))
    print("  Curtosis:", kurtosis(subset))

# Cuartiles
cuartiles_tip = tips['tip'].quantile([0.25, 0.5, 0.75])
cuartiles_tip

# Diagrama de cajas
plt.figure(figsize=(6,5))
sns.boxplot(y=tips['tip'])
plt.title("Diagrama de cajas de Tip")
plt.show()

"""<h2 style="color:#b36b00; margin-top:0;">2. Datos Atípicos (Outliers) <span style='font-size:0.7em; color:#888;'>&#9888;&#65039;</span></h2>
<p style="font-size:1.1em;">
En este apartado identificarás y analizarás <b>outliers univariados y multivariados</b> usando diferentes datasets y técnicas.
</p>
<div style="background:#fff2cc; border-left:4px solid #b36b00; padding:10px 18px; border-radius:8px; margin-bottom:10px;">
<b>Univariado:</b> <br>
Utiliza el dataset <code>ds_salaries.csv</code> (en la misma ruta que este notebook).
<ol style="font-size:1.05em;">
<li><b>Análisis exploratorio:</b> Visualiza la distribución y diagramas de caja de cada variable. Agrega comentarios sobre tus hallazgos.</li>
<li><b>Identificación de outliers:</b> Aplica métodos vistos en clase según la distribución de cada variable.</li>
</ol>
</div>
<div style="background:#ffe6e6; border-left:4px solid #b30000; padding:10px 18px; border-radius:8px;">
<b>Multivariado:</b> <br>
Descarga y utiliza el dataset <a href="https://drive.google.com/file/d/19dZnyQcZzrQMkGWKETd-577r_SAN-Vfv/view?usp=drive_link" target="_blank"><code>credit_card.csv</code></a>.
<ol style="font-size:1.05em;">
<li><b>Identificación de outliers multivariados:</b> Aplica técnicas multivariadas vistas en clase para detectar valores atípicos.</li>
</ol>
</div>

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2

from google.colab import files
uploaded = files.upload()

import pandas as pd

credit = pd.read_csv("ds_salaries.csv")

print("ANÁLISIS UNIVARIADO")

numeric_cols_s = salaries.select_dtypes(include='number').columns.tolist()
print("Columnas numéricas:", numeric_cols_s)

for col in numeric_cols_s:

    print(f"\n--- Variable: {col} ---\n")
    print(salaries[col].describe())

    # Histograma
    plt.figure(figsize=(7,4))
    sns.histplot(salaries[col], kde=True)
    plt.title(f"Histograma de {col}")
    plt.show()

    # Boxplot
    plt.figure(figsize=(7,2))
    sns.boxplot(x=salaries[col])
    plt.title(f"Boxplot de {col}")
    plt.show()

import pandas as pd

salaries = pd.read_csv("ds_salaries.csv")

print("OUTLIERS")

def outliers_iqr(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    mask = (series < lower) | (series > upper)
    return mask, lower, upper

for col in numeric_cols_s:
    mask, low, up = outliers_iqr(salaries[col])
    print(f"{col}: {mask.sum()} outliers detectados (IQR)")
    print(f"Rango permitido: [{low}, {up}]\n")

from google.colab import files
uploaded = files.upload()

# DETECCIÓN DE OUTLIERS MULTIVARIADOS

import pandas as pd
import numpy as np
from scipy.stats import chi2

credit = pd.read_csv("creditcard.csv")

numeric_cols_c = credit.select_dtypes(include='number').columns.tolist()
numeric_cols_c = [col for col in numeric_cols_c if col != "Class"]

X = credit[numeric_cols_c].dropna()

cov = np.cov(X, rowvar=False)

if np.linalg.det(cov) == 0:
    print("⚠ La matriz de covarianza es singular. Aplicando regularización.")
    cov = cov + 1e-6 * np.eye(cov.shape[0])

inv_cov = np.linalg.inv(cov)
mean = X.mean().values

def mahalanobis(x):
    diff = x - mean
    return np.sqrt(diff.T @ inv_cov @ diff)

md = X.apply(mahalanobis, axis=1)

credit["Mahalanobis"] = md

print("Columna Mahalanobis creada correctamente.")
print(credit[["Mahalanobis"]].head())

df = len(numeric_cols_c)
threshold = np.sqrt(chi2.ppf(0.999, df))
print("Umbral:", threshold)

outliers_mult = credit[credit["Mahalanobis"] > threshold]
print("Outliers detectados:", len(outliers_mult))

outliers_mult.head()

