# -*- coding: utf-8 -*-
"""Actividad1_Extracción-VEML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FLJEAUX5aRA778DKQpRcSeOkfMPaHM4

<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='alinco.png' width="120"/>
<h1 style="color:#000047;">Actividad 1: Extracción de datos de diferentes fuentes</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> Practicar la extracción, análisis y manipulación de datos provenientes de archivos JSON, XML, CSV e imágenes usando Python.
</div>

<div style="margin-top:10px;">
<b>Instrucciones generales:</b>
<ul>
<li>Lee cuidadosamente cada sección y realiza los ejercicios propuestos.</li>
<li>Utiliza <b>pandas</b> para manipulación de datos tabulares, <b>json</b> y <b>xml.etree.ElementTree</b> para extracción de datos, y <b>matplotlib</b> o <b>opencv</b> para imágenes.</li>
<li>Responde cada pregunta con código y, cuando sea necesario, justifica tu respuesta.</li>
</ul>
</div>

## 1️⃣ JSON: Información de empleados

Supón que tienes el archivo <code>empleados.json</code> con la siguiente estructura:

```json
[
  {"nombre": "Ana", "edad": 28, "departamento": "Ventas", "salario": 2500},
  {"nombre": "Luis", "edad": 35, "departamento": "IT", "salario": 3200},
  {"nombre": "María", "edad": 24, "departamento": "Ventas", "salario": 2300},
  {"nombre": "Carlos", "edad": 40, "departamento": "IT", "salario": 4000}
]
```

<b>Ejercicios:</b>

1. Crea un DataFrame a partir de la extracción de información de este archivo JSON.
2. ¿Cuál es el <b>salario promedio por departamento</b>?
3. ¿Quién es el <b>empleado más joven</b> y a qué departamento pertenece?
4. ¿Cuántos empleados tienen un <b>salario mayor a 2500</b>?
5. ¿Cuál es la <b>diferencia de edad</b> entre el empleado más joven y el de mayor edad?
6. ¿Cuál es el <b>salario total pagado</b> en la empresa?

<i>Tip: Usa pandas.read_json o json.load para cargar los datos.</i>
"""

import pandas as pd
import json

data_json = '''
[
    {"nombre": "Ana", "edad": 28, "departamento": "Ventas", "salario": 2500},
    {"nombre": "Luis", "edad": 35, "departamento": "IT", "salario": 3200},
    {"nombre": "María", "edad": 24, "departamento": "Ventas", "salario": 2300},
    {"nombre": "Carlos", "edad": 40, "departamento": "IT", "salario": 4000}
]
'''
empleados = pd.read_json(data_json)
print("=== DataFrame de empleados ===")
print(empleados)
print()

salario_promedio = empleados.groupby('departamento')['salario'].mean()
print("=== Salario promedio por departamento ===")
print(salario_promedio)
print()

empleado_joven = empleados.loc[empleados['edad'].idxmin()]
print("=== Empleado más joven ===")
print(f"Nombre: {empleado_joven['nombre']}, Edad: {empleado_joven['edad']}, Departamento: {empleado_joven['departamento']}")
print()

empleados_mayor_2500 = empleados[empleados['salario'] > 2500]
print("=== Empleados con salario mayor a 2500 ===")
print(empleados_mayor_2500[['nombre', 'salario']])
print(f"Total de empleados con salario > 2500: {len(empleados_mayor_2500)}")
print()

edad_min = empleados['edad'].min()
edad_max = empleados['edad'].max()
diferencia_edad = edad_max - edad_min
print("=== Diferencia de edad ===")
print(f"Diferencia de edad entre el más joven ({edad_min}) y el mayor ({edad_max}) es: {diferencia_edad} años")
print()

salario_total = empleados['salario'].sum()
print("=== Salario total pagado en la empresa ===")
print(f"${salario_total}")

"""## 2️⃣ XML: Catálogo de libros

Supón que tienes el archivo libros.xml con la siguiente estructura:

```csv
<libros>
  <libro>
    <titulo>Python para Todos</titulo>
    <autor>Juan Pérez</autor>
    <precio>29.99</precio>
    <anio>2020</anio>
  </libro>
  <libro>
    <titulo>Data Science Avanzado</titulo>
    <autor>María López</autor>
    <precio>45.50</precio>
    <anio>2022</anio>
  </libro>
  <libro>
    <titulo>Ingeniería de Características</titulo>
    <autor>Pedro Ruiz</autor>
    <precio>39.00</precio>
    <anio>2019</anio>
  </libro>
</libros>
```

<b>Ejercicios:</b>

1. Crea un DataFrame a partir de la extracción de información de este archivo XML.
2. ¿Cuál es el libro más caro y su autor?
3. ¿Cuál es el precio promedio de los libros publicados después de 2020?
4. ¿Cuántos libros fueron publicados antes de 2021?
5. ¿Cuál es la diferencia de precio entre el libro más barato y el más caro?
6. ¿Cuántos autores diferentes hay en la lista?

<i>Tip: Usa xml.etree.ElementTree para leer el archivo y pandas para tabular los datos.</i>
"""

import xml.etree.ElementTree as ET
import pandas as pd
from io import StringIO
data_xml = """
<libros>
    <libro>
        <titulo>Python para Todos</titulo>
        <autor>Juan Pérez</autor>
        <precio>29.99</precio>
        <anio>2020</anio>
    </libro>
    <libro>
        <titulo>Data Science Avanzado</titulo>
        <autor>María López</autor>
        <precio>45.50</precio>
        <anio>2022</anio>
    </libro>
    <libro>
        <titulo>Ingeniería de Características</titulo>
        <autor>Pedro Ruiz</autor>
        <precio>39.00</precio>
        <anio>2019</anio>
    </libro>
</libros>
"""

root = ET.parse(StringIO(data_xml)).getroot()

libros = []
for libro in root.findall('libro'):
    titulo = libro.find('titulo').text
    autor = libro.find('autor').text
    precio = float(libro.find('precio').text)
    anio = int(libro.find('anio').text)
    libros.append({'titulo': titulo, 'autor': autor, 'precio': precio, 'anio': anio})

df = pd.DataFrame(libros)
print("=== DataFrame de libros ===")
print(df)
print()

libro_mas_caro = df.loc[df['precio'].idxmax()]
print("=== Libro más caro ===")
print(f"Título: {libro_mas_caro['titulo']}, Autor: {libro_mas_caro['autor']}, Precio: {libro_mas_caro['precio']}")
print()

promedio_post_2020 = df[df['anio'] > 2020]['precio'].mean()
print("=== Precio promedio de libros publicados después de 2020 ===")
print(f"${promedio_post_2020:.2f}")
print()

libros_antes_2021 = df[df['anio'] < 2021]
print("=== Libros publicados antes de 2021 ===")
print(libros_antes_2021[['titulo', 'anio']])
print(f"Total: {len(libros_antes_2021)} libros")
print()

diferencia_precio = df['precio'].max() - df['precio'].min()
print("=== Diferencia de precio ===")
print(f"${diferencia_precio:.2f}")
print()

autores_unicos = df['autor'].nunique()
print("=== Autores diferentes ===")
print(f"Total de autores diferentes: {autores_unicos}")

"""## 3️⃣ CSV: Ventas detalladas

Supón que tienes el archivo <code>ventas_detalladas.csv</code> con la siguiente estructura:

```csv
producto,fecha,cantidad,precio_unitario
A,2023-01-01,10,2.5
B,2023-01-02,5,3.0
A,2023-01-03,7,2.5
C,2023-01-01,3,4.0
B,2023-01-03,2,3.0
```

<b>Ejercicios:</b>

1. Crea un DataFrame con los datos extraídos del archivo.
2. ¿Cuál es el <b>total vendido</b> por producto y por fecha?
3. ¿En qué fecha se vendió la <b>mayor cantidad de productos</b>?
4. ¿Cuál es el <b>producto con mayor ingreso total</b>?
5. ¿Cuál es la <b>media de cantidad vendida</b> por producto?
6. ¿Qué producto tuvo <b>ventas todos los días registrados</b>?

<i>Tip: Usa pandas.read_csv y agrupa los datos según lo que se pide.</i>
"""

import pandas as pd
from io import StringIO

data_csv = """
producto,fecha,cantidad,precio_unitario
A,2023-01-01,10,2.5
B,2023-01-02,5,3.0
A,2023-01-03,7,2.5
C,2023-01-01,3,4.0
B,2023-01-03,2,3.0
"""
ventas = pd.read_csv(StringIO(data_csv))
print("=== DataFrame de ventas ===")
print(ventas)
print()

ventas["total"] = ventas["cantidad"] * ventas["precio_unitario"]

total_por_producto = ventas.groupby("producto")["total"].sum()
total_por_fecha = ventas.groupby("fecha")["total"].sum()

print("=== Total vendido por producto ===")
print(total_por_producto)
print("\n=== Total vendido por fecha ===")
print(total_por_fecha)
print()

cantidad_por_fecha = ventas.groupby("fecha")["cantidad"].sum()
fecha_mayor_cantidad = cantidad_por_fecha.idxmax()
print("=== Fecha con mayor cantidad de productos vendidos ===")
print(f"Fecha: {fecha_mayor_cantidad}, Cantidad total: {cantidad_por_fecha.max()}")
print()

producto_mayor_ingreso = total_por_producto.idxmax()
print("=== Producto con mayor ingreso total ===")
print(f"Producto: {producto_mayor_ingreso}, Total vendido: {total_por_producto.max()}")
print()

media_cantidad = ventas.groupby("producto")["cantidad"].mean()
print("=== Media de cantidad vendida por producto ===")
print(media_cantidad)
print()

dias_totales = ventas["fecha"].nunique()


ventas_por_dia = ventas.groupby("producto")["fecha"].nunique()

producto_todos_dias = ventas_por_dia[ventas_por_dia == dias_totales].index.tolist()

print("=== Producto(s) con ventas todos los días registrados ===")
if producto_todos_dias:
    print(producto_todos_dias)
else:
    print("Ningún producto tuvo ventas todos los días registrados.")

"""## 4️⃣ Imágenes: Análisis de pixeles

Supón que tienes la imagen <code>alinco.png</code> en la misma carpeta que este notebook.

<b>Ejercicios:</b>

1. Extrae la información de los pixeles de la imagen y muestra sus dimensiones.
2. ¿Cuál es el <b>valor RGB</b> del píxel (50, 50)?
3. ¿Cuál es el <b>color predominante</b> en la imagen?

<i>Tip: Usa matplotlib.pyplot.imread o cv2.imread para cargar la imagen y numpy para analizar los datos.</i>
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

imagen = cv2.imread("alinco.png")
imagen_rgb = cv2.cvtColor(imagen, cv2.COLOR_BGR2RGB)
alto, ancho, canales = imagen_rgb.shape
print(f"Dimensiones de la imagen: {ancho} x {alto} píxeles y {canales} canales (RGB)")
pixel_50_50 = imagen_rgb[50, 50]
print(f"Valor RGB del píxel (50, 50): {pixel_50_50}")
color_promedio = imagen_rgb.mean(axis=(0, 1)).astype(int)
print(f"Color promedio (predominante) en la imagen (RGB): {color_promedio}")
plt.imshow(imagen_rgb)
plt.title("Imagen: alinco.png")
plt.axis("off")
plt.show()